#macro SLIMESPEED                   2
#macro SLIMEWIDTH                  33
#macro SLIMEHEIGHT                 22
#macro CROUCHEDSLIMEWIDTH  SLIMEWIDTH
#macro CROUCHEDSLIMEHEIGHT         14
#macro CRABWIDTH                   32
#macro CRABHEIGHT                  32
#macro CRABSPEED           SLIMESPEED
#macro FALLINGSPEED                 3
#macro SMOKESPEED          SLIMESPEED
#macro SMOKEWIDTH                  32